"""
The main purpose of having this simple script is to be more familiar with data
processing with pandas and the side effect is having a 'tool' to convert the 
two DDF files generated by M172 IDE into one modbus register map file by csv 
format which is easy to be imported in excel.

2021.02.17 First created
"""

import pandas as pd
import numpy as np

# %%
if __name__ == '__main__':
    VARIABLES_FILENAME = "BZ172Lab Status Variables.CSV"
    EEPROM_FILENAME = "E2PROM Parameters.CSV"
    
    # load sheets  
    dfVariables = pd.read_csv(VARIABLES_FILENAME, 
                              encoding='ansi',
                              dtype=str,
                              delimiter=',',
                              usecols=[0, 1, 3, 5, 6, 7, 8, 11, 14, 15, 16])
    dfConfigurations = pd.read_csv(EEPROM_FILENAME, 
                                   encoding='ansi',
                                   dtype=str,
                                   usecols=[0, 1, 3, 5, 6, 7, 8, 11, 14, 15])

    # Add 'RW' to dfConfigurations
    ReadOnly = ['RW'] * len(dfConfigurations)    
    dfConfigurations.insert(loc=9, column='ReadOnly', value=ReadOnly)

    # Combine the two dataframes and replace 'na' with blank
    ddf = pd.concat([dfVariables, dfConfigurations])
    ddf = ddf.fillna('')
    
    # Update index
    ddf.index=[x for x in range(0, len(ddf))]
    
    # Remove 'BZ...' items
    ddf = ddf.drop(index=ddf[ddf['Name'].str.match('BZ')].index)

    # Fill the 'Size' of 16bit items with '1'
    ddf.loc[ddf[ddf['Size'] == ''].index, 'Size'] = '1'
    
    # Remove 'bz' and 'Cfg' from names
    ddf.Name = ddf.Name.str.replace('bz', '')
    ddf.Min = ddf.Min.str.replace('bz', '')
    ddf.Max = ddf.Max.str.replace('bz', '')
    
    # Sort by address
    ddf.loc[:, 'Address'] = ddf.Address.astype('ushort')
    ddf = ddf.sort_values(by='Address', ascending=True)
    
    # save to csv file with utf-8 format by default
    ddf.to_csv('BZ172LabDDF.csv')
